/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CategoryId = bigint;
export type ProductId = bigint;
export interface T {
  'id' : ProductId,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'price' : bigint,
}
export interface T__1 { 'productId' : ProductId, 'quantity' : bigint }
export interface T__2 {
  'id' : CategoryId,
  'name' : string,
  'description' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCategory' : ActorMethod<[T__2], undefined>,
  'addProduct' : ActorMethod<[T], undefined>,
  'addToCart' : ActorMethod<[ProductId, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'deleteCategory' : ActorMethod<[CategoryId], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'getAllCategories' : ActorMethod<[], Array<T__2>>,
  'getAllProducts' : ActorMethod<[], Array<T>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCartTotal' : ActorMethod<[], bigint>,
  'getProductById' : ActorMethod<[ProductId], [] | [T]>,
  'getUserCart' : ActorMethod<[], Array<T__1>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeFromCart' : ActorMethod<[ProductId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProducts' : ActorMethod<[string], Array<T>>,
  'updateCartQuantity' : ActorMethod<[ProductId, bigint], undefined>,
  'updateProduct' : ActorMethod<[ProductId, T], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];