/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CategoryId = IDL.Nat;
export const T__2 = IDL.Record({
  'id' : CategoryId,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const ProductId = IDL.Nat;
export const T = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const T__1 = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCategory' : IDL.Func([T__2], [], []),
  'addProduct' : IDL.Func([T], [], []),
  'addToCart' : IDL.Func([ProductId, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'deleteCategory' : IDL.Func([CategoryId], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'getAllCategories' : IDL.Func([], [IDL.Vec(T__2)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(T)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCartTotal' : IDL.Func([], [IDL.Nat], ['query']),
  'getProductById' : IDL.Func([ProductId], [IDL.Opt(T)], ['query']),
  'getUserCart' : IDL.Func([], [IDL.Vec(T__1)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFromCart' : IDL.Func([ProductId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(T)], ['query']),
  'updateCartQuantity' : IDL.Func([ProductId, IDL.Nat], [], []),
  'updateProduct' : IDL.Func([ProductId, T], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CategoryId = IDL.Nat;
  const T__2 = IDL.Record({
    'id' : CategoryId,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const ProductId = IDL.Nat;
  const T = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const T__1 = IDL.Record({ 'productId' : ProductId, 'quantity' : IDL.Nat });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCategory' : IDL.Func([T__2], [], []),
    'addProduct' : IDL.Func([T], [], []),
    'addToCart' : IDL.Func([ProductId, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'deleteCategory' : IDL.Func([CategoryId], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'getAllCategories' : IDL.Func([], [IDL.Vec(T__2)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(T)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCartTotal' : IDL.Func([], [IDL.Nat], ['query']),
    'getProductById' : IDL.Func([ProductId], [IDL.Opt(T)], ['query']),
    'getUserCart' : IDL.Func([], [IDL.Vec(T__1)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFromCart' : IDL.Func([ProductId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(T)], ['query']),
    'updateCartQuantity' : IDL.Func([ProductId, IDL.Nat], [], []),
    'updateProduct' : IDL.Func([ProductId, T], [], []),
  });
};

export const init = ({ IDL }) => { return []; };